export const GET_MOVIE_CONFIG_REQUEST = 'GET_MOVIE_CONFIG_REQUEST';
export const GET_MOVIE_CONFIG_SUCCESS = 'GET_MOVIE_CONFIG_SUCCESS';
export const GET_MOVIE_CONFIG_FAILED = 'GET_MOVIE_CONFIG_FAILED';

export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILED = 'GET_ALL_MOVIES_FAILED';