export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAILED = 'GET_ALL_MOVIES_FAILED';

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';

export const GET_SHOWS_REQUEST = 'GET_SHOWS_REQUEST';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_FAILED = 'GET_SHOWS_FAILED';

export const GET_SHOW_REQUEST = 'GET_SHOW_REQUEST';
export const GET_SHOW_SUCCESS = 'GET_SHOW_SUCCESS';
export const GET_SHOW_FAILED = 'GET_SHOW_FAILED';

export const GET_SHOW_ACTORS_REQUEST = 'GET_SHOW_ACTORS_REQUEST';
export const GET_SHOW_ACTORS_SUCCESS = 'GET_SHOW_ACTORS_SUCCESS';
export const GET_SHOW_ACTORS_FAILED = 'GET_SHOW_ACTORS_FAILED';